clear all;


home_figures_path = '/home/yusipov/Work/os_d/figures';

data_path = '/data/biophys/yusipov/os_d';
prefix = 'qjx_results';

data_path = sprintf('%s/%s', data_path, prefix);

sys_id = 1;
task_id = 2;
prop_id = 0;
num_trajectories = 1;
num_tp_periods = 100;
num_obs_periods = 10;
seed = 0;
mns = 1000000;
ex_deep = 4;
rk_ns = 10000;

N = 200;
diss_type = 0;
diss_gamma = 0.1;
diss_phase = 0;
jcs_drv_part_1 = 0.98;
jcs_drv_part_2 = 1;
jcs_drv_ampl = 0.1;
jcs_prm_alpha = 5;
start_type = 0;
start_state = 0;
deep_num_steps = 10000;

sys_size = N;

num_runs = 1;

ampl_begin = 0.01;
ampl_step = 0.01;
ampl_num = 1;

eps_start = 1.0e-8;
eps_per_decade = 10;
eps_num = 81;

m_begin = 1;
m_step = 1;
m_num = 5;

for ampl_id = 1:ampl_num
    
    ampl_id = ampl_id;
    ampl = ampl_begin + ampl_step * (ampl_id - 1)
    
    fig = figure;
    
    for m_id = 1:m_num
        
        m = m_begin + m_step * (m_id - 1)
        
        epss = zeros(eps_num, 1);
        cis = zeros(eps_num, 1);
        
        for eps_id = 1:eps_num
            
            eps = eps_start * 10.0^((eps_id-1)/eps_per_decade)
            
            epss(eps_id) = eps;
            
            for run_id = 1:num_runs
                
                ss = (run_id - 1) * num_trajectories;                
                
                path_to_folder = sprintf('%s/main_%d_%d_%d/run_%d_%d_%d_%d/ci_%d_%d_%0.10f/N_%d/diss_%d_%0.4f_%0.4f/drv_%0.4f_%0.4f_%0.4f/prm_%0.4f/start_%d_%d/ss_%d', ...
                    data_path, ...
                    sys_id, ...
                    task_id, ...
                    prop_id, ...
                    ex_deep, ...
                    rk_ns, ...
                    num_tp_periods, ...
                    num_obs_periods, ...
                    deep_num_steps, ...
                    m, ...
                    eps, ...
                    N, ...
                    diss_type, ...
                    diss_gamma, ...
                    diss_phase, ...
                    jcs_drv_part_1, ...
                    jcs_drv_part_2, ...
                    ampl, ...
                    jcs_prm_alpha, ...
                    start_type, ...
                    start_state, ...
                    ss);
                
                suffix = sprintf('config(%d_%d_%d)_rnd(%d_%d)_N(%d)_diss(%d_%0.4f_%0.4f)_drv(%0.4f_%0.4f_%0.4f)_prm(%0.4f)_start(%d_%d)', ...
                    sys_id, ...
                    task_id, ...
                    prop_id, ...
                    ss, ...
                    mns, ...
                    N, ...
                    diss_type, ...
                    diss_gamma, ...
                    diss_phase, ...
                    jcs_drv_part_1, ...
                    jcs_drv_part_2, ...
                    ampl, ...
                    jcs_prm_alpha, ...
                    start_type, ...
                    start_state);
                
                
                fn = sprintf('%s/ci_%s.txt', path_to_folder, suffix);
                data = importdata(fn);
                
                cis(eps_id) = cis(eps_id) + data;
            end
            
            cis(eps_id) = cis(eps_id) / num_runs;
            
        end
        
        hLine = plot(log10(epss), log10(cis), 'LineWidth', 2);
        legend(hLine, sprintf('%d', m_id));
        
        set(gca, 'FontSize', 30);
        xlabel('$\log_{10}(\epsilon)$', 'Interpreter', 'latex');
        
        set(gca, 'FontSize', 30);
        ylabel('$\log_{10}(C)$', 'Interpreter', 'latex');
        
        hold all;
        
    end
    
   suffix = sprintf('config(%d_%d_%d)_rnd(%d_%d)_N(%d)_diss(%d_%0.4f_%0.4f)_drv(%0.4f_%0.4f_var)_prm(%0.4f)_start(%d_%d)', ...
            sys_id, ...
			task_id, ...
			prop_id, ...
			ss, ...
            mns, ...
            N, ...
            diss_type, ...
            diss_gamma, ...
            diss_phase, ...
			jcs_drv_part_1, ...
            jcs_drv_part_2, ...
            jcs_prm_alpha, ...
            start_type, ...
            start_state);
    
    savefig(sprintf('%s/cd_%s.fig', home_figures_path, suffix));
    
end
