clear all;

home_figures_path = '/home/denysov/yusipov/os_d/figures';

data_path = '/data/biophys/denysov/yusipov/os_d/data/qjx';


sys_id = 1; 
task_id = 7; 
prop_id = 0; 
seed = 0; 
mns = 1000000;
num_trajectories = 20;
num_tp_periods = 100;
num_obs_periods = 100; 
ex_deep = 16;
rk_ns = 10000;
 
T = 1.0;
 
N = 200; 
diss_type = 1; 
diss_gamma = 0.1; 
diss_phase = 0; 
jcs_drv_part_1 = 1.0 * T; 
jcs_drv_part_2 = 1.0 * T;
jcs_prm_alpha = 5; 
start_type = 0; 
start_state = 0; 


num_runs = 1;

ampl_begin = 0.05;
ampl_step = 0.05;
ampl_num = 100;
ampls = zeros(ampl_num, 1);
lambdas = zeros(ampl_num, 1);

for ampl_id = 1:ampl_num
	
	ampl_id = ampl_id
	ampl = ampl_begin + ampl_step * (ampl_id - 1);
	ampls(ampl_id) = ampl;
	
	for run_id = 1:num_runs
        
        ss = (run_id - 1) * num_trajectories;
        
		path_to_folder = sprintf('%s/main_%d_%d_%d/run_%d_%d_%d_%d/N_%d/diss_%d_%0.4f_%0.4f/drv_%0.4f_%0.4f_%0.4f/prm_%0.4f/start_%d_%d/ss_%d', ...
			data_path, ...
            sys_id, ...
			task_id, ...
			prop_id, ...
            ex_deep, ...
			rk_ns, ...
            num_tp_periods, ...
            num_obs_periods, ...
            N, ...
            diss_type, ...
            diss_gamma, ...
            diss_phase, ...
            jcs_drv_part_1, ...
            jcs_drv_part_2, ...
            ampl, ...
            jcs_prm_alpha, ...
            start_type, ...
            start_state, ...
            ss);
        
        suffix = sprintf('rnd(%d_%d)_N(%d)_diss(%d_%0.4f_%0.4f)_drv(%0.4f_%0.4f_%0.4f)_prm(%0.4f)_start(%d_%d)', ...
			ss, ...
            mns, ...
            N, ...
            diss_type, ...
            diss_gamma, ...
            diss_phase, ...
			jcs_drv_part_1, ...
            jcs_drv_part_2, ...
            ampl, ...
            jcs_prm_alpha, ...
            start_type, ...
            start_state);
       
      
		path = sprintf('%s/lambda_%s.txt', path_to_folder, suffix);
		data = importdata(path);
		
		lambdas(ampl_id) = lambdas(ampl_id) + mean(data(num_trajectories / 2 + 1:end));

	end
	
	lambdas(ampl_id) = lambdas(ampl_id) / num_runs;
    
end

suffix = sprintf('config(%d_%d_%d)_rnd(%d_%d)_N(%d)_drv(%0.4f_%0.4f_var)_prm(%0.4f)_start(%d_%d)', ...
            sys_id, ...
			task_id, ...
			prop_id, ...
			ss, ...
            mns, ...
            N, ...
			jcs_drv_part_1, ...
            jcs_drv_part_2, ...
            jcs_prm_alpha, ...
            start_type, ...
            start_state);

fig = figure;
hLine = plot(ampls, lambdas);
set(gca, 'FontSize', 30);
xlabel('$A$', 'Interpreter', 'latex');
set(gca, 'FontSize', 30);
ylabel('$\lambda$', 'Interpreter', 'latex');

savefig(sprintf('%s/lambda_from_ampl_%s.fig', home_figures_path, suffix));

h=gcf;
set(h,'PaperOrientation','landscape');
set(h,'PaperUnits','normalized');
set(h,'PaperPosition', [0 0 1 1]);
print(gcf, '-dpdf', sprintf('%s/lambda_from_ampl_%s.pdf', home_figures_path, suffix));
