clear all;

home_figures_path = '/home/denysov/yusipov/os_d/figures';

data_path = '/data/biophys/denysov/yusipov/os_d/data/qjx';


sys_id = 1;
task_id = 7;
prop_id = 0;
seed = 0;
mns = 1000000;
num_trajectories = 20;
num_tp_periods = 100;
num_obs_periods = 100;
ex_deep = 16;
rk_ns = 10000;

N = 200;
diss_type = 1;
diss_gamma = 0.1;
diss_phase = 0;
jcs_drv_part_1 = 0.98;
jcs_drv_part_2 = 1.0;
jcs_prm_alpha = 5;
start_type = 0;
start_state = 0;

num_runs = 1;

ampl_begin = 0.05;
ampl_step = 0.05;
ampl_num = 100;
ampls = linspace(ampl_begin, ampl_begin + (ampl_num - 1) * ampl_step, ampl_num);

T_begin = 0.05;
T_step = 0.05;
T_num = 100;
Ts = linspace(T_begin * (jcs_drv_part_1 + jcs_drv_part_2) * jcs_prm_alpha, (T_begin + (T_num - 1) * T_step) * (jcs_drv_part_1 + jcs_drv_part_2) * jcs_prm_alpha, T_num);

lambdas = zeros(ampl_num, T_num);

for T_id = 1:T_num
    
    T = T_begin + T_step * (T_id - 1)
    
    for ampl_id = 1:ampl_num
        
        ampl = ampl_begin + ampl_step * (ampl_id - 1);
        
        for run_id = 1:num_runs
            
            ss = (run_id - 1) * num_trajectories;
            
            path_to_folder = sprintf('%s/main_%d_%d_%d/run_%d_%d_%d_%d/N_%d/diss_%d_%0.4f_%0.4f/drv_%0.4f_%0.4f_%0.4f/prm_%0.4f/start_%d_%d/ss_%d', ...
                data_path, ...
                sys_id, ...
                task_id, ...
                prop_id, ...
                ex_deep, ...
                rk_ns, ...
                num_tp_periods, ...
                num_obs_periods, ...
                N, ...
                diss_type, ...
                diss_gamma, ...
                diss_phase, ...
                jcs_drv_part_1 * T, ...
                jcs_drv_part_2 * T, ...
                ampl, ...
                jcs_prm_alpha, ...
                start_type, ...
                start_state, ...
                ss);
            
            suffix = sprintf('rnd(%d_%d)_N(%d)_diss(%d_%0.4f_%0.4f)_drv(%0.4f_%0.4f_%0.4f)_prm(%0.4f)_start(%d_%d)', ...
                ss, ...
                mns, ...
                N, ...
                diss_type, ...
                diss_gamma, ...
                diss_phase, ...
                jcs_drv_part_1 * T, ...
                jcs_drv_part_2 * T, ...
                ampl, ...
                jcs_prm_alpha, ...
                start_type, ...
                start_state);
            
            
            path = sprintf('%s/lambda_%s.txt', path_to_folder, suffix);
            data = importdata(path);
            
            lambdas(ampl_id, T_id) = lambdas(ampl_id, T_id) + mean(data(num_trajectories / 2 + 1:end));
        end
    end
end

lambdas = lambdas / num_runs;

suffix = sprintf('config(%d_%d_%d)_rnd(%d_%d)_N(%d)_drv(%0.4f_%0.4f_var)_prm(%0.4f)_start(%d_%d)', ...
    sys_id, ...
    task_id, ...
    prop_id, ...
    ss, ...
    mns, ...
    N, ...
    jcs_drv_part_1, ...
    jcs_drv_part_2, ...
    jcs_prm_alpha, ...
    start_type, ...
    start_state);

fig = figure;
hLine = imagesc(ampls, Ts, lambdas');
set(gca, 'FontSize', 30);
xlabel('$A$', 'Interpreter', 'latex');
set(gca, 'FontSize', 30);
ylabel('$T$', 'Interpreter', 'latex');
colormap hot;
h = colorbar;
set(gca, 'FontSize', 30);
title(h, '\lambda');
set(gca,'YDir','normal');


savefig(sprintf('%s/lambda_from_ampl_and_T_%s.fig', home_figures_path, suffix));
