clear all;

home_figures_path = '/home/yusipov/Work/os_d/figures';

data_path = '/data/biophys/yusipov/os_d';
prefix = 'qjx_results';

data_path = sprintf('%s/%s', data_path, prefix);

sys_id = 1; 
task_id = 0; 
prop_id = 0; 
seed = 0; 
mns = 1000000;
num_trajectories = 50;
num_tp_periods = 1000;
num_obs_periods = 5000; 
ex_deep = 16;
rk_ns = 10000;
 
lpn = 1.0e-2;
 
N = 200; 
diss_type = 0; 
diss_gamma = 0.1; 
diss_phase = 0; 
jcs_drv_part_1 = 0.98; 
jcs_drv_part_2 = 1;
jcs_drv_ampl = 0.1; 
jcs_prm_alpha = 5; 
start_type = 0; 
start_state = 0; 

sys_size = N;

num_runs = 1;

ss = 0;

alpha_begin = 0.025;
alpha_step = 0.025;
alpha_num = 200;
alphas = linspace(alpha_begin, alpha_num * alpha_step, alpha_num);

T_begin = 0.025;
T_step = 0.025;
T_num = 200;
Ts = linspace(T_begin, T_num * T_step, T_num);

lpns = zeros(alpha_num, T_num);

for alpha_id = 1:alpha_num
	
	alpha = alpha_begin + alpha_step * (alpha_id - 1)

	for T_id = 1:T_num
	 
        T = T_begin + T_step * (T_id - 1);
        
		path_to_folder = sprintf('%s/main_%d_%d_%d/run_%d_%d_%d_%d/N_%d/diss_%d_%0.4f_%0.4f/drv_%0.4f_%0.4f_%0.4f/prm_%0.4f/start_%d_%d/ss_%d', ...
			data_path, ...
            sys_id, ...
			task_id, ...
			prop_id, ...
            ex_deep, ...
			rk_ns, ...
            num_tp_periods, ...
            num_obs_periods, ...
            N, ...
            diss_type, ...
            diss_gamma, ...
            diss_phase, ...
            0.98 * T, ...
            1.00 * T, ...
            alpha, ...
            jcs_prm_alpha, ...
            start_type, ...
            start_state, ...
            ss);
        
        suffix = sprintf('config(%d_%d_%d)_rnd(%d_%d)_N(%d)_diss(%d_%0.4f_%0.4f)_drv(%0.4f_%0.4f_%0.4f)_prm(%0.4f)_start(%d_%d)', ...
            sys_id, ...
			task_id, ...
			prop_id, ...
			ss, ...
            mns, ...
            N, ...
            diss_type, ...
            diss_gamma, ...
            diss_phase, ...
			0.98 * T, ...
            1.00 * T, ...
            alpha, ...
            jcs_prm_alpha, ...
            start_type, ...
            start_state);
       
      
		path = sprintf('%s/lambda_%s.txt', path_to_folder, suffix);
		data = importdata(path);
		
		curr_lpns = data(2:end);
        
        mean_lpn = mean(curr_lpns);
        
        lpns(alpha_id, T_id) = mean_lpn;
       
	end
    
end

suffix = sprintf('config(%d_%d_%d)_rnd(%d_%d)_N(%d)_diss(%d_%0.4f_%0.4f)_prm(%0.4f)_start(%d_%d)', ...
            sys_id, ...
			task_id, ...
			prop_id, ...
			ss, ...
            mns, ...
            N, ...
            diss_type, ...
            diss_gamma, ...
            diss_phase, ...
            jcs_prm_alpha, ...
            start_type, ...
            start_state);

        
fig = figure;
hLine = imagesc(alphas, Ts, lpns');
set(gca, 'FontSize', 30);
xlabel('$A$', 'Interpreter', 'latex');
set(gca, 'FontSize', 30);
ylabel('$T$', 'Interpreter', 'latex');
colormap hot;
h = colorbar;
set(gca, 'FontSize', 30);
title(h, '\lambda');
set(gca,'YDir','normal');

savefig(sprintf('%s/lambda_color_%s.fig', home_figures_path, suffix));
