clear all;

home_figures_path = '/home/yusipov/Work/os_d/figures';

data_path = '/data/biophys/yusipov/os_d';
prefix = 'qjx_results';

data_path = sprintf('%s/%s', data_path, prefix);

sys_id = 1;
task_id = 1;
prop_id = 0;
seed = 0;
mns = 1000000;
num_trajectories = 1;
num_tp_periods = 1000;
num_obs_periods = 10000;
ex_deep = 10;
rk_ns = 10000;

N = 200;
diss_type = 0;
diss_gamma = 0.1;
diss_phase = 0;
jcs_drv_part_1 = 0.98;
jcs_drv_part_2 = 1;
jcs_drv_ampl = 1.44;
jcs_prm_alpha = 5;
start_type = 0;
start_state = 0;

sys_size = N;

num_runs = 10;

ampl_begin = 0.1;
ampl_step = 0.1;
ampl_num = 50;
ampls = zeros(ampl_num, 1);

spec_begin = -3.0;
spec_end = 3.0;
spec_num = 500;
spec_shift = (spec_end - spec_begin) / spec_num;
specs = zeros(spec_num, 1);
for spec_id = 1 : spec_num
    specs(spec_id) = spec_begin + ((spec_id - 1) + 0.5) * spec_shift;
end

pdf = zeros(spec_num, spec_num);

non_inc = 0;

for run_id = 1:num_runs
    
    ss = (run_id - 1) * num_trajectories;
    
    path_to_folder = sprintf('%s/main_%d_%d_%d/run_%d_%d_%d_%d/N_%d/diss_%d_%0.4f_%0.4f/drv_%0.4f_%0.4f_%0.4f/prm_%0.4f/start_%d_%d/ss_%d', ...
        data_path, ...
        sys_id, ...
        task_id, ...
        prop_id, ...
        ex_deep, ...
        rk_ns, ...
        num_tp_periods, ...
        num_obs_periods, ...
        N, ...
        diss_type, ...
        diss_gamma, ...
        diss_phase, ...
        jcs_drv_part_1, ...
        jcs_drv_part_2, ...
        jcs_drv_ampl, ...
        jcs_prm_alpha, ...
        start_type, ...
        start_state, ...
        ss);
    
    suffix = sprintf('config(%d_%d_%d)_rnd(%d_%d)_N(%d)_diss(%d_%0.4f_%0.4f)_drv(%0.4f_%0.4f_%0.4f)_prm(%0.4f)_start(%d_%d)', ...
        sys_id, ...
        task_id, ...
        prop_id, ...
        ss, ...
        mns, ...
        N, ...
        diss_type, ...
        diss_gamma, ...
        diss_phase, ...
        jcs_drv_part_1, ...
        jcs_drv_part_2, ...
        jcs_drv_ampl, ...
        jcs_prm_alpha, ...
        start_type, ...
        start_state);
    
    
    path = sprintf('%s/spec_evo_%s.txt', path_to_folder, suffix);
    data = importdata(path);
    data_size = size(data, 1);
    
    for d_id = 1:data_size
        
        curr_re = data(d_id, 1);
        curr_im = data(d_id, 2);
        
        if ((curr_re >= spec_begin) && (curr_re <= spec_end) && (curr_im >= spec_begin) && (curr_im <= spec_end))
        
            int_re_id = floor((curr_re - spec_begin) * spec_num / (spec_end - spec_begin + 10e-8)) + 1;
            int_im_id = floor((curr_im - spec_begin) * spec_num / (spec_end - spec_begin + 10e-8)) + 1;
            
            pdf(int_re_id, int_im_id) = pdf(int_re_id, int_im_id) + 1;
            
        else
            non_inc = non_inc + 1;
        end
        
    end
    
end

non_inc = non_inc

count = sum(sum(pdf))

pdf = pdf / (count * spec_shift * spec_shift);

norm = sum(sum(pdf)) * spec_shift * spec_shift

fig = figure;
hLine = imagesc(specs, specs, pdf');
set(gca, 'FontSize', 30);
xlabel('$Re(\theta)$', 'Interpreter', 'latex');
set(gca, 'FontSize', 30);
ylabel('$Im(\theta)$', 'Interpreter', 'latex');
colormap hot;
h = colorbar;
set(gca, 'FontSize', 30);
title(h, '$PDF$', 'FontSize', 33, 'interpreter','latex');
set(gca,'YDir','normal');

suffix = sprintf('config(%d_%d_%d)_rnd(%d_%d)_N(%d)_diss(%d_%0.4f_%0.4f)_drv(%0.4f_%0.4f_%0.4f)_prm(%0.4f)_start(%d_%d)', ...
    sys_id, ...
    task_id, ...
    prop_id, ...
    ss, ...
    mns, ...
    N, ...
    diss_type, ...
    diss_gamma, ...
    diss_phase, ...
    jcs_drv_part_1, ...
    jcs_drv_part_2, ...
    jcs_drv_ampl, ...
    jcs_prm_alpha, ...
    start_type, ...
    start_state);

savefig(sprintf('%s/spec_%s.fig', home_figures_path, suffix));
