clear all;

home_figures_path = '/home/denysov/yusipov/os_d/figures';
data_path = '/data/biophys/denysov/yusipov/os_d/data/qjx';

T = 2.0;
num_trajectories = 10;
num_runs = 1;

sys_id = 1;
task_id = 1;
prop_id = 0;

ex_deep = 16;
rk_ns = 10000;
num_tp_periods = 100;
num_obs_periods = 10000;

N = 200;

diss_type = 0;

jcs_drv_part_1 = 1.0 * T;
jcs_drv_part_2 = 1.0 * T;
jcs_drv_ampl = 4.0;

jcs_prm_alpha = 5.0;

start_type = 0;
start_state = 0;

seed = 0;
mns = 1000000;

suffix_save = sprintf('N(%d)_diss(%d)_drv(%0.4f_%0.4f_%0.4f)_prm(%0.4f)_start(%d_%d)', ...
    N, ...
    diss_type, ...
    jcs_drv_part_1, ...
    jcs_drv_part_2, ...
	jcs_drv_ampl, ...
    jcs_prm_alpha, ...
    start_type, ...
    start_state);

for run_id = 1:num_runs
    
    ss = (run_id - 1) * num_trajectories;
    
    path_to_folder = sprintf('%s/main_%d_%d_%d/run_%d_%d_%d_%d/N_%d/diss_%d/drv_%0.4f_%0.4f_%0.4f/prm_%0.4f/start_%d_%d/ss_%d', ...
        data_path, ...
        sys_id, ...
        task_id, ...
        prop_id, ...
        ex_deep, ...
        rk_ns, ...
        num_tp_periods, ...
        num_obs_periods, ...
        N, ...
        diss_type, ...
        jcs_drv_part_1, ...
        jcs_drv_part_2, ...
        jcs_drv_ampl, ...
        jcs_prm_alpha, ...
        start_type, ...
        start_state, ...
        ss);
    
    suffix = sprintf('rnd(%d_%d)_N(%d)_diss(%d_%0.4f_%0.4f)_drv(%0.4f_%0.4f_%0.4f)_prm(%0.4f)_start(%d_%d)', ...
        ss, ...
        mns, ...
        N, ...
        diss_type, ...
        0.1, ...
        0.0, ...
        jcs_drv_part_1, ...
        jcs_drv_part_2, ...
        jcs_drv_ampl, ...
        jcs_prm_alpha, ...
        start_type, ...
        start_state);
    
    for trajectory_id = 1:num_trajectories
        
        path = sprintf('%s/jump_times_%d_%s.txt', path_to_folder, trajectory_id - 1, suffix);
        jump_times = importdata(path);
        
        path = sprintf('%s/jump_etas_%d_%s.txt', path_to_folder, trajectory_id - 1, suffix);
        jump_etas = importdata(path);
        
        num_sections = size(jump_times, 1);
        
        fid = fopen(sprintf('%s/tr_%d_%s.txt', home_figures_path, num_trajectories * (run_id - 1) + trajectory_id,  suffix_save),'wt');
        
        for section_id = 2:num_sections
            curr_time = jump_times(section_id) - jump_times(section_id - 1);
            curr_dist = -log10(jump_etas(section_id));
            curr_v = curr_dist / curr_time;
            
            fprintf(fid,'%0.16e %0.16e\n', curr_time, curr_v);
        end
        
        fclose(fid);
    end
end
