clear all;

path_figures = 'D:/YandexDisk/Work/os_d/drafts/floquet/two_spins/lambdas';
path_data = 'D:/Work/os_d/source/cpp/QJX/QJX';

sys_id = 7;
task_id = 7;
prop_id = 1;
seed = 1;
mns = 1000000;

num_trajectories = 50;
num_tp_periods = 100;
num_obs_periods = 100;

Delta_1 = 1.0;
Delta_2 = 1.0;
J = 1.0;
gamma = 0.05;

lpn_type = -1;
lpn_delta_s = log10(1.0e-6);
lpn_delta_f_high = log10(1.0e-6);
lpn_delta_f_low = log10(1.0e-6);

ampl_start = 2.0;
ampl_shift = 2.0;
ampl_num = 50;
ampls = linspace(ampl_start, ampl_start + (ampl_num - 1) * ampl_shift, ampl_num);

freq_start = 0.2;
freq_shift = 0.2;
freq_num = 50;
freqs = linspace(freq_start, freq_start + (freq_num - 1) * freq_shift, freq_num);

lambdas = zeros(ampl_num, freq_num);

for freq_id = 1:freq_num
    freq = freq_start + (freq_id - 1) * freq_shift
    for ampl_id = 1:ampl_num
        ampl = ampl_start + (ampl_id - 1) * ampl_shift;

        suffix = sprintf('setup(%d_%d_%d)_rnd(%d_%d)_ampl(%0.4f)_freq(%0.4f)_D1(%0.4f)_D2(%0.4f)_J(%0.4f)_gamma(%0.4f)_lpn(%d_%0.4f_%0.4f_%0.4f)', ...
            sys_id, ...
            task_id, ...
            prop_id, ...
            seed, ...
            mns, ...
            ampl, ...
            freq, ...
            Delta_1, ...
            Delta_2, ...
            J, ...
            gamma, ...
            lpn_type, ...
            lpn_delta_s, ...
            lpn_delta_f_high, ...
            lpn_delta_f_low);

        path = sprintf('%s/lambda_%s.txt', path_data, suffix);
        data = importdata(path);

        lambdas(ampl_id, freq_id) = lambdas(ampl_id, freq_id) + mean(data(num_trajectories / 2 + 1:end));
    end  
end

fig = figure;
hLine = imagesc(ampls, freqs, lambdas');
set(gca, 'FontSize', 30);
xlabel('$A$', 'Interpreter', 'latex');
set(gca, 'FontSize', 30);
ylabel('$\omega$', 'Interpreter', 'latex');
colormap hot;
h = colorbar;
set(gca, 'FontSize', 30);
title(h, '$\lambda$', 'FontSize', 33, 'interpreter','latex');
set(gca,'YDir','normal');
hold all;

suffix = sprintf('traj(%d)_tp(%d)_obs(%d)_ampl(%0.4f_%0.4f_%d)_freq(%0.4f_%0.4f_%d)_D1(%0.4f)_D2(%0.4f)_J(%0.4f)_gamma(%0.4f)_lpn(%d_%0.4f_%0.4f_%0.4f)', ...
            num_trajectories, ...
            num_tp_periods, ...
            num_obs_periods, ...
            ampl_start, ...
            ampl_shift, ...
            ampl_num, ...
            freq_start, ...
            freq_shift, ...
            freq_num, ...
            Delta_1, ...
            Delta_2, ...
            J, ...
            gamma, ...
            lpn_type, ...
            lpn_delta_s, ...
            lpn_delta_f_high, ...
            lpn_delta_f_low);

fn_fig = sprintf('%s/lambdas_%s', path_figures, suffix);
oqs_save_fig(fig, fn_fig);