from infrastructure.path import *


def create_files(config):
    path = get_data_path(config)

    file_config = open(path + '/config.txt', 'w')

    file_config.write('sys_id ' + str(config.run.quantum_system.value) + '\n')
    file_config.write('task_id ' + str(config.run.process.value) + '\n')
    file_config.write('prop_id ' + str(config.run.propagation.value) + '\n')
    file_config.write('ex_deep ' + str(config.details.step_metrics) + '\n')
    file_config.write('rk_ns ' + str(config.details.step_metrics) + '\n')
    file_config.write('num_tp_periods ' + str(config.details.num_periods_trans.value) + '\n')
    file_config.write('num_obs_periods ' + str(config.details.num_periods_obser.value) + '\n')
    file_config.write('seed ' + str(config.random.seed.value) + '\n')
    file_config.write('mns ' + str(config.random.num_seeds.value) + '\n')
    file_config.write('is_debug ' + str(config.auxiliary['is_debug']) + '\n')
    file_config.write('is_pp ' + str(config.auxiliary['is_pp']) + '\n')
    file_config.write('init_fn ' + str(config.auxiliary['init_fn']) + '\n')
    file_config.write('path ' + str(config.auxiliary['path']) + '\n')
    file_config.write('num_threads ' + str(config.auxiliary['num_threads']) + '\n')
    file_config.write('num_trajectories ' + str(config.auxiliary['num_trajectories']) + '\n')
    file_config.close()

    file_params = open(path + '/params.txt', 'w')

    file_params.write('lpn_type ' + str(lpn_type) + '\n')
    file_params.write('lpn_eps ' + str(lpn_eps) + '\n')
    file_params.write('lpn_eps_change ' + str(lpn_eps_change) + '\n')
    file_params.write('lpn_delta_s_high ' + str(lpn_delta_s_high) + '\n')
    file_params.write('lpn_delta_s_low ' + str(lpn_delta_s_low) + '\n')
    file_params.write('lpn_delta_f_high ' + str(lpn_delta_f_high) + '\n')
    file_params.write('lpn_delta_f_low ' + str(lpn_delta_f_low) + '\n')
    file_params.write('dump_obs ' + str(dump_obs) + '\n')
    file_params.write('dump_adr_sep ' + str(dump_adr_sep) + '\n')
    file_params.write('dump_adr_avg ' + str(dump_adr_avg) + '\n')
    file_params.write('dump_evo_sep ' + str(dump_evo_sep) + '\n')
    file_params.write('dump_evo_avg ' + str(dump_evo_avg) + '\n')
    file_params.write('dump_type ' + str(dump_type) + '\n')
    file_params.write('dump_num ' + str(dump_num) + '\n')
    file_params.write('N ' + str(N) + '\n')
    file_params.write('diss_type ' + str(diss_type) + '\n')
    file_params.write('diss_gamma ' + str(diss_gamma) + '\n')
    file_params.write('diss_phase ' + str(diss_phase) + '\n')
    file_params.write('dimer_drv_type ' + str(dimer_drv_type) + '\n')
    file_params.write('dimer_drv_ampl ' + str(dimer_drv_ampl) + '\n')
    file_params.write('dimer_drv_freq ' + str(dimer_drv_freq) + '\n')
    file_params.write('dimer_drv_phase ' + str(dimer_drv_phase) + '\n')
    file_params.write('dimer_prm_E ' + str(dimer_prm_E) + '\n')
    file_params.write('dimer_prm_U ' + str(dimer_prm_U) + '\n')
    file_params.write('dimer_prm_J ' + str(dimer_prm_J) + '\n')
    file_params.write('jcs_drv_part_1 ' + str(jcs_drv_part_1) + '\n')
    file_params.write('jcs_drv_part_2 ' + str(jcs_drv_part_2) + '\n')
    file_params.write('jcs_drv_ampl ' + str(jcs_drv_ampl) + '\n')
    file_params.write('jcs_prm_alpha ' + str(jcs_prm_alpha) + '\n')
    file_params.write('start_type ' + str(start_type) + '\n')
    file_params.write('start_state ' + str(start_state) + '\n')
    file_params.write('cd_dim ' + str(cd_dim) + '\n')
    file_params.write('cd_eps ' + str(cd_eps) + '\n')
    file_params.write('deep_num_steps ' + str(deep_num_steps) + '\n')
    file_params.write('deep_dump ' + str(deep_dump) + '\n')
    file_params.write('jump ' + str(jump))

    file_params.close()