clear all;

home_figures_path = '/home/yusipov/Work/os_d/figures';

data_path = '/data/biophys/yusipov/os_d';
prefix = 'mf_results';

data_path = sprintf('%s/%s', data_path, prefix);

task = 3;
U = 1.56;
seed_start = 0;
seed_num = 1;
path = ''; 
mt = 0;
num_steps = 10000;
npt = 10000;
np = 10000;
E = 1.0;
A = 1.5 ;
omega = 1.0;
phase = 0.0;
gamma = 0.1;
J = 1.0;

N = 1000;

num_hits = 0;

fig = figure;

for seed = 1:seed_num
    
    path_to_folder = sprintf('%s/task_%d/mt_%d/omega_%0.4f/phase_%0.4f/g_%0.4f/J_%0.4f/E_%0.4f/A_%0.4f/U_%0.4f/seed_%d', ...
        data_path, ...
        task, ...
        mt, ...
        omega, ...
        phase, ...
        gamma, ...
        J, ...
        E, ...
        A, ...
        U, ...
        seed);
    
    fn_suffix = sprintf('mt(%d)_omega(%0.4f)_phase(%0.4f)_g(%0.4f)_J(%0.4f)_E(%0.4f)_A(%0.4f)_U(%0.4f)_seed(%d).txt', ...
        mt, ...
        omega, ...
        phase, ...
        gamma, ...
        J, ...
        E, ...
        A, ...
        U, ...
        seed);
    
    fn = sprintf('%s/data_%s', path_to_folder, fn_suffix);
    data = importdata(fn);
    
	time = data(2:end, 1);
    nu = data(2:end, 2);
    
    coordinate = N/2*(cos(nu)+1);
	
	hLine = scatter(time, coordinate);
	set(gca, 'FontSize', 30);
	xlabel('$t$', 'Interpreter', 'latex');
	set(gca, 'FontSize', 30);
	ylabel('$x(t)$', 'Interpreter', 'latex');
	hold all;
	
end

fn_suffix = sprintf('mt(%d)_omega(%0.4f)_phase(%0.4f)_g(%0.4f)_J(%0.4f)_E(%0.4f)_A(%0.4f)_U(%0.4f)_seed_num(%d)', ...
    mt, ...
    omega, ...
    phase, ...
    gamma, ...
    J, ...
    E, ...
    A, ...
    U, ...
    seed_num);

savefig(sprintf('%s/mf_x_evo_%s.fig', home_figures_path, fn_suffix));
