clear all;


home_figures_path = '/home/yusipov/Work/os_d/figures';

data_path = '/data/biophys/yusipov/os_d';
prefix = 'qjx_results';

data_path = sprintf('%s/%s', data_path, prefix);

sys_id = 0;
task_id = 2;
prop_id = 0;
num_trajectories = 1;
num_tp_periods = 100;
num_obs_periods = 10;
seed = 0;
mns = 1000000;
ex_deep = 4;
rk_ns = 10000;

N = 100;
diss_type = 0;
diss_gamma = 0.1;
diss_phase = 0.0;
dimer_drv_type = 0;
dimer_drv_ampl = 1.5;
dimer_drv_freq = 1.0;
dimer_drv_phase = 0.0;
start_type = 0;
start_state = 0;
dimer_prm_E = 1.0;
dimer_prm_J = 1.0;
deep_num_steps = 10000;

sys_size = N + 1;

num_runs = 1;

U_begin = 0.01;
U_step = 0.01;
U_num = 1;

eps_start = 1.0e-8;
eps_per_decade = 10;
eps_num = 81;

m_begin = 1;
m_step = 1;
m_num = 5;

for U_id = 1:U_num
    
    U_id = U_id;
    U = U_begin + U_step * (U_id - 1)
    
    fig = figure;
    
    for m_id = 1:m_num
        
        m = m_begin + m_step * (m_id - 1)
        
        epss = zeros(eps_num, 1);
        cis = zeros(eps_num, 1);
        
        for eps_id = 1:eps_num
            
            eps = eps_start * 10.0^((eps_id-1)/eps_per_decade)
            
            epss(eps_id) = eps;
            
            for run_id = 1:num_runs
                
                ss = (run_id - 1) * num_trajectories;
                
                path_to_folder = sprintf('%s/main_%d_%d_%d/run_%d_%d_%d_%d/ci_%d_%d_%0.10f/N_%d/diss_%d_%0.4f_%0.4f/drv_%d_%0.4f_%0.4f_%0.4f/prm_%0.4f_%0.4f_%0.4f/start_%d_%d/ss_%d', ...
                    data_path, ...
                    sys_id, ...
					task_id, ...
                    prop_id, ...
                    ex_deep, ...
                    rk_ns, ...
                    num_tp_periods, ...
                    num_obs_periods, ...
                    deep_num_steps, ...
                    m, ...
                    eps, ...
                    N, ...
                    diss_type, ...
                    diss_gamma, ...
                    diss_phase, ...
                    dimer_drv_type, ...
                    dimer_drv_ampl, ...
                    dimer_drv_freq, ...
                    dimer_drv_phase, ...
                    dimer_prm_E, ...
                    U, ...
                    dimer_prm_J, ...
                    start_type, ...
                    start_state, ...
                    ss);
                
                suffix = sprintf('config(%d_%d_%d)_rnd(%d_%d)_N(%d)_diss(%d_%0.4f_%0.4f)_drv(%d_%0.4f_%0.4f_%0.4f)_prm(%0.4f_%0.4f_%0.4f)_start(%d_%d)', ...
                    sys_id, ...
                    task_id, ...
                    prop_id, ...
                    ss, ...
                    mns, ...
                    N, ...
                    diss_type, ...
                    diss_gamma, ...
                    diss_phase, ...
                    dimer_drv_type, ...
                    dimer_drv_ampl, ...
                    dimer_drv_freq, ...
                    dimer_drv_phase, ...
                    dimer_prm_E, ...
                    U, ...
                    dimer_prm_J, ...
                    start_type, ...
                    start_state);
                
                
                fn = sprintf('%s/ci_%s.txt', path_to_folder, suffix);
                data = importdata(fn);
                
                cis(eps_id) = cis(eps_id) + data;
            end
            
            cis(eps_id) = cis(eps_id) / num_runs;
            
        end
        
        hLine = plot(log10(epss), log10(cis), 'LineWidth', 2);
        legend(hLine, sprintf('%d', m_id));
        
        set(gca, 'FontSize', 30);
        xlabel('$\log_{10}(\epsilon)$', 'Interpreter', 'latex');
        
        set(gca, 'FontSize', 30);
        ylabel('$\log_{10}(C)$', 'Interpreter', 'latex');
        
        hold all;
        
    end
    
    suffix = sprintf('trj(%d)_N(%d)_diss(%d_%0.4f_%0.4f)_drv(%d_%0.4f_%0.4f_%0.4f)_prm(%0.4f_%0.4f_%0.4f)_start(%d_%d).txt', ...
        num_runs * num_trajectories, ...
        N, ...
        diss_type, ...
        diss_gamma, ...
        diss_phase, ...
        dimer_drv_type, ...
        dimer_drv_ampl, ...
        dimer_drv_freq, ...
        dimer_drv_phase, ...
        dimer_prm_E, ...
        U, ...
        dimer_prm_J, ...
        start_type, ...
        start_state);
    
    savefig(sprintf('%s/cd_%s.fig', home_figures_path, suffix));
    
end
