clear all;

home_figures_path = '/home/yusipov/Work/os_d/figures';

data_path = '/data/biophys/yusipov/os_d';
prefix = 'qjx_results';

data_path = sprintf('%s/%s', data_path, prefix);

sys_id = 0;
task_id = 0;
prop_id = 0;
is_debug = 0;
is_pp = 1;
init_fn = '';
path = '';
num_threads = 1;
ex_deep = 16;
rk_num_steps = 10000;
num_tp_periods = 2000;
num_obs_periods = 1000;
num_trajectories = 50;
seed = 0;
mns = 1000000;

lpn = 1.0e-2;
N = 100;
diss_type = 0;
diss_gamma = 0.1;
diss_phase = 0.0;
dimer_drv_type = 0;
dimer_drv_ampl = 3.4;
dimer_drv_freq = 1.0;
dimer_drv_phase = 0.0;
start_type = 0;
start_state = 0;
dimer_prm_E = 1.0;
dimer_prm_U = 0;
dimer_prm_J = 1.0;

ss = 0;

num_runs = 1;

U_begin = 0.01;
U_step = 0.01;
U_num = 200;
Us = linspace(U_begin, U_num * U_step, U_num);

A_begin = 0.01;
A_step = 0.01;
A_num = 200;
As = linspace(A_begin, A_num * A_step, A_num);

lpns = zeros(U_num, A_num);

for U_id = 1:U_num
    
    U = U_begin + (U_id - 1) * U_step
	
    for A_id = 1:A_num
        
        A = A_begin + (A_id - 1) * A_step;
        
        path_to_folder = sprintf('%s/main_%d_%d_%d/run_%d_%d_%d_%d/lpn_%0.4f/N_%d/diss_%d_%0.4f_%0.4f/drv_%d_%0.4f_%0.4f_%0.4f/prm_%0.4f_%0.4f_%0.4f/start_%d_%d/ss_%d', ...
            data_path, ...
            sys_id, ...
            task_id, ...
            prop_id, ...
            ex_deep, ...
            rk_num_steps, ...
            num_tp_periods, ...
            num_obs_periods, ...
            lpn, ...
            N, ...
            diss_type, ...
            diss_gamma, ...
            diss_phase, ...
            dimer_drv_type, ...
            A, ...
            dimer_drv_freq, ...
            dimer_drv_phase, ...
            dimer_prm_E, ...
            U, ...
            dimer_prm_J, ...
            start_type, ...
            start_state, ...
            ss);
        
        suffix = sprintf('config(%d_%d_%d)_rnd(%d_%d)_N(%d)_diss(%d_%0.4f_%0.4f)_drv(%d_%0.4f_%0.4f_%0.4f)_prm(%0.4f_%0.4f_%0.4f)_start(%d_%d)', ...
            sys_id, ...
            task_id, ...
            prop_id, ...
            ss, ...
            mns, ...
            N, ...
            diss_type, ...
            diss_gamma, ...
            diss_phase, ...
            dimer_drv_type, ...
            A, ...
            dimer_drv_freq, ...
            dimer_drv_phase, ...
            dimer_prm_E, ...
            U, ...
            dimer_prm_J, ...
            start_type, ...
            start_state);
        
        
        path = sprintf('%s/lambda_%s.txt', path_to_folder, suffix);
        data = importdata(path);
        curr_lpns = data(2:end);
        
        mean_lpn = mean(curr_lpns);
        
        lpns(U_id, A_id) = mean_lpn;
        
    end  
end
        
fig = figure;
hLine = imagesc(Us, As, lpns');
set(gca, 'FontSize', 30);
xlabel('$U$', 'Interpreter', 'latex');
set(gca, 'FontSize', 30);
ylabel('$A$', 'Interpreter', 'latex');
colormap hot;
h = colorbar;
set(gca, 'FontSize', 30);
title(h, '\lambda');
set(gca,'YDir','normal');

suffix = sprintf('main(%d_%d_%d)_N(%d)_diss(%d_%0.4f_%0.4f)_drv(%d_%0.4f_%0.4f_%0.4f)_prm(%0.4f_%0.4f_%0.4f)_start(%d_%d).txt', ...
            sys_id, ...
			prop_id, ...
			task_id, ...
            N, ...
            diss_type, ...
            diss_gamma, ...
            diss_phase, ...
            dimer_drv_type, ...
            dimer_drv_ampl, ...
            dimer_drv_freq, ...
            dimer_drv_phase, ...
            dimer_prm_E, ...
            dimer_prm_U, ...
            dimer_prm_J, ...
            start_type, ...
            start_state);
		
savefig(sprintf('%s/lambda_color_%s.fig', home_figures_path, suffix));