clear all;

home_figures_path = '/home/denysov/yusipov/os_d/figures';
data_path = '/data/biophys/denysov/yusipov/os_d/data/qjx';

sys_id = 0;
task_id = 7;
prop_id = 0;

ex_deep = 16;
rk_ns = 10000;
num_tp_periods = 1000;
num_obs_periods = 1000;

num_rnd_obs = 1;
rnd_obs_seed = 100;
rnd_obs_type = 2;

N = 500;

diss_type = 0;
diss_gamma = 0.1;
diss_phase = 0.0;

dimer_drv_type = 0;
dimer_drv_ampl = 1.5;
dimer_drv_freq = 1.0;
dimer_drv_phase = 0.0;

dimer_prm_E = 1.0;
dimer_prm_J = 1.0;

start_type = 0;
start_state = 0;

ss = 0;
mns = 1000000;

num_trajectories = 20;
num_target_traj = 10;
num_runs = 1;

sys_size = N + 1;

U_begin = 0.01;
U_step = 0.01;
U_num = 100;

lpn_type = -1;
lpn_delta_f_h = 1e-1;
lpn_delta_s = 1e-3;
lpn_delta_f_l = 1e-5;

Us = zeros(U_num, 1);
lambdas = zeros(U_num, 1);

for U_id = 1:U_num
    
    U = U_begin + U_step * (U_id - 1)
    Us(U_id) = U;
    
    curr_lambdas = 0;
    
    for run_id = 1:num_runs
        
        ss = (run_id - 1) * num_trajectories;
        
        path_to_folder = sprintf('%s/main_%d_%d_%d/lpn_%d_%0.4f_%0.4f_%0.4f/run_%d_%d_%d_%d/obs_%d_%d_%d/N_%d/diss_%d_%0.4f_%0.4f/drv_%d_%0.4f_%0.4f_%0.4f/prm_%0.4f_%0.4f_%0.4f/start_%d_%d/ss_%d', ...
            data_path, ...
            sys_id, ...
            task_id, ...
            prop_id, ...
			lpn_type, ...
			log10(lpn_delta_s), ...
			log10(lpn_delta_f_h), ...
			log10(lpn_delta_f_l), ...
            ex_deep, ...
            rk_ns, ...
            num_tp_periods, ...
            num_obs_periods, ...
			num_rnd_obs, ...
			rnd_obs_seed, ...
			rnd_obs_type, ...
            N, ...
            diss_type, ...
            diss_gamma, ...
            diss_phase, ...
            dimer_drv_type, ...
            dimer_drv_ampl, ...
            dimer_drv_freq, ...
            dimer_drv_phase, ...
            dimer_prm_E, ...
            U, ...
            dimer_prm_J, ...
            start_type, ...
            start_state, ...
            ss);
        
        suffix = sprintf('setup(%d_%d_%d)_rnd(%d_%d)_N(%d)_diss(%d_%0.4f_%0.4f)_drv(%d_%0.4f_%0.4f_%0.4f)_prm(%0.4f_%0.4f_%0.4f)_start(%d_%d)_lpn(%d_%0.4f_%0.4f_%0.4f)', ...
            sys_id, ...
            task_id, ...
            prop_id, ...
			ss, ...
            mns, ...
            N, ...
            diss_type, ...
            diss_gamma, ...
            diss_phase, ...
            dimer_drv_type, ...
            dimer_drv_ampl, ...
            dimer_drv_freq, ...
            dimer_drv_phase, ...
            dimer_prm_E, ...
            U, ...
            dimer_prm_J, ...
            start_type, ...
            start_state, ...
			lpn_type, ...
			log10(lpn_delta_s), ...
			log10(lpn_delta_f_h), ...
			log10(lpn_delta_f_l));
        
        fn = sprintf('%s/lambda_%s.txt', path_to_folder, suffix);
        lambda_data = importdata(fn);
        curr_lambdas = curr_lambdas + mean(lambda_data(num_target_traj + 1 : end));
    end
    
    curr_lambdas = curr_lambdas / num_runs;
    
    lambdas(U_id) = curr_lambdas;
    
end

fig = figure;
hLine = plot(Us, lambdas);
set(gca, 'FontSize', 30);
xlabel('$U$', 'Interpreter', 'latex');
set(gca, 'FontSize', 30);
ylabel('$\lambda$', 'Interpreter', 'latex');
xlim([Us(1) Us(end)])

suffix_save = sprintf('run_(%d_%d_%d_%d)_N(%d)_diss(%d_%0.4f_%0.4f)_drv(%d_%0.4f_%0.4f_%0.4f)_prm(%0.4f_var_%0.4f)_start(%d_%d)_lpn(%d_%0.4f_%0.4f_%0.4f)', ...
    ex_deep, ...
    rk_ns, ...
    num_tp_periods, ...
    num_obs_periods, ...
	N, ...
    diss_type, ...
    diss_gamma, ...
    diss_phase, ...
    dimer_drv_type, ...
    dimer_drv_ampl, ...
    dimer_drv_freq, ...
    dimer_drv_phase, ...
    dimer_prm_E, ...
    dimer_prm_J, ...
    start_type, ...
    start_state, ...
	lpn_type, ...
	log10(lpn_delta_s), ...
	log10(lpn_delta_f_h), ...
	log10(lpn_delta_f_l));

savefig(sprintf('%s/lambda_from_U_%s.fig', home_figures_path, suffix_save));

h=gcf;
set(h,'PaperOrientation','landscape');
set(h,'PaperUnits','normalized');
set(h,'PaperPosition', [0 0 1 1]);
print(gcf, '-dpdf', sprintf('%s/lambda_from_U_%s.pdf', home_figures_path, suffix_save));

