clear all;

home_figures_path = '/home/denysov/yusipov/os_d/figures';
data_path = '/data/biophys/denysov/yusipov/os_d/data/qjx';

sys_id = 0;
task_id = 7;
prop_id = 1;

ex_deep = 16;
rk_ns = 10000;
num_tp_periods = 100;
num_obs_periods = 100;

N = 100;

diss_type = 0;
diss_gamma = 0.1;
diss_phase = 0.0;

dimer_drv_type = 1;
dimer_drv_ampl = 3.4;
dimer_drv_freq = 1.0;
dimer_drv_phase = 0.0;

dimer_prm_E = 0.0;
dimer_prm_J = 1.0;

start_type = 0;
start_state = 0;

ss = 0;
mns = 1000000;

num_trajectories = 20;
num_target_traj = 10;
num_runs = 10;

sys_size = N + 1;

U_begin = 0.01;
U_step = 0.01;
U_num = 100;

Us = zeros(U_num, 1);
mean_maxes = zeros(U_num, 1);

for U_id = 1:U_num
    
    U = U_begin + U_step * (U_id - 1)
    Us(U_id) = U;
    
    curr_mean_maxes = 0;
    
    for run_id = 1:num_runs
        
        ss = (run_id - 1) * num_trajectories;
        
        path_to_folder = sprintf('%s/main_%d_%d_%d/run_%d_%d_%d_%d/N_%d/diss_%d_%0.4f_%0.4f/drv_%d_%0.4f_%0.4f_%0.4f/prm_%0.4f_%0.4f_%0.4f/start_%d_%d/ss_%d', ...
            data_path, ...
            sys_id, ...
            task_id, ...
            prop_id, ...
            ex_deep, ...
            rk_ns, ...
            num_tp_periods, ...
            num_obs_periods, ...
            N, ...
            diss_type, ...
            diss_gamma, ...
            diss_phase, ...
            dimer_drv_type, ...
            dimer_drv_ampl, ...
            dimer_drv_freq, ...
            dimer_drv_phase, ...
            dimer_prm_E, ...
            U, ...
            dimer_prm_J, ...
            start_type, ...
            start_state, ...
            ss);
        
        suffix = sprintf('rnd(%d_%d)_N(%d)_diss(%d_%0.4f_%0.4f)_drv(%d_%0.4f_%0.4f_%0.4f)_prm(%0.4f_%0.4f_%0.4f)_start(%d_%d)', ...
            ss, ...
            mns, ...
            N, ...
            diss_type, ...
            diss_gamma, ...
            diss_phase, ...
            dimer_drv_type, ...
            dimer_drv_ampl, ...
            dimer_drv_freq, ...
            dimer_drv_phase, ...
            dimer_prm_E, ...
            U, ...
            dimer_prm_J, ...
            start_type, ...
            start_state);
        
        fn = sprintf('%s/mean_evo_%s.txt', path_to_folder, suffix);
        mean_evo_data = importdata(fn);
        
        maxes = zeros(num_target_traj, 1);
        
        for tr_id = 1:num_target_traj
            
            mean_evo_base = mean_evo_data(:, tr_id);
            mean_evo_var = mean_evo_data(:, tr_id + num_target_traj);
            
            mean_evo_diff = abs(mean_evo_base - mean_evo_var) / sys_size;
            
            pks = findpeaks(mean_evo_diff);
            maxes(tr_id) = mean(pks);
        end
        
        curr_mean_maxes = curr_mean_maxes + mean(maxes);
        
    end
    
    curr_mean_maxes = curr_mean_maxes / num_runs;
    
    mean_maxes(U_id) = curr_mean_maxes;
    
end

fig = figure;
hLine = plot(Us, mean_maxes);
set(gca, 'FontSize', 30);
xlabel('$U$', 'Interpreter', 'latex');
set(gca, 'FontSize', 30);
ylabel('$mean maxes$', 'Interpreter', 'latex');
xlim([Us(1) Us(end)])

suffix_save = sprintf('N(%d)_diss(%d_%0.4f_%0.4f)_drv(%d_%0.4f_%0.4f_%0.4f)_prm(%0.4f_var_%0.4f)_start(%d_%d)', ...
    N, ...
    diss_type, ...
    diss_gamma, ...
    diss_phase, ...
    dimer_drv_type, ...
    dimer_drv_ampl, ...
    dimer_drv_freq, ...
    dimer_drv_phase, ...
    dimer_prm_E, ...
    dimer_prm_J, ...
    start_type, ...
    start_state);

savefig(sprintf('%s/mean_maxes_from_U_%s.fig', home_figures_path, suffix_save));

h=gcf;
set(h,'PaperOrientation','landscape');
set(h,'PaperUnits','normalized');
set(h,'PaperPosition', [0 0 1 1]);
print(gcf, '-dpdf', sprintf('%s/mean_maxes_from_U_%s.pdf', home_figures_path, suffix_save));

